class CityInfoState:
    data = dict()
    # city = data['user_id']['city']
    # destination_id = data['user_id']['destination_id']
    # arrival_date = data['user_id']['arrival_date']
    # departure_date = data['user_id']['departure_date']
    # days_in_hotel = data['user_id']['days_in_hotel']
    # criterion = data['user_id']['criterion']
    # currency = data['user_id']['currency']
    # need_photo = data['user_id']['need_photo']
    # count_photo = data['user_id']['count_photo']
    # hotels_count = data['user_id']['hotels_count']
    # distance_from_center = data['user_id']['distance_from_center']
    # max_cost = data['user_id']['max_cost']
    # min_cost = data['user_id']['min_cost']
